---
# new_key_cert_options:
#   type: root_ca = self_signed), other = root_ca/SUB_root_ca signed)
#   delete:
  
#   cert_name:
#   cert_country_code:
#   cert_country:
#   cert_locality:
#   cert_organisation:
#   cert_organisational_unit:
#   cert_subj:
#   cert_subj_alt:
#   cert_email:
#   cert_digest:
#   cert_ocsp_staple:
#   cert_ocsp_staple_crt:

#   key_usage:
#   key_usage_crt:
#   key_ext_usage:
#   key_ext_crt:
#   key_cipher:
#   key_curve:
#   key_pass:
#   key_size:
#   key_type:


- name: Create root CA certificate
  block:
    - set_fact:
        root_ca_key_cert_options_overide: "{{ 
          root_ca_key_cert_options|combine(root_ca_key_options_template)|combine(
            {
            'name': root_ca_key_cert_options.cert_common_name|d(root_ca_key_cert_options.cert_name)|d(root_ca_key_cert_options.name)
            }
          )|combine(
              { 'base_path': certificates_base_path+'/root-ca/'+root_ca_key_cert_options.cert_common_name|d(root_ca_key_cert_options.cert_name)|d(root_ca_key_cert_options.name) }
            if not root_ca_key_cert_options.base_path|d(false) else
              {}
          )
          }}"

    - set_fact:
        key_cert_options_overide: "{{ root_ca_key_cert_options_overide }}"
    - include_tasks: generate_csr.yml

    - name: Sign root CA certificate request
      local_action:
        module: community.crypto.x509_certificate
        select_crypto_backend: cryptography
        path: "{{ root_ca_key_cert_options_overide.base_path }}/cert.pem"
        csr_path: "{{ root_ca_key_cert_options_overide.base_path }}/csr.pem"
        provider: selfsigned
        privatekey_path: "{{ root_ca_key_cert_options_overide.base_path }}/key.pem"
        privatekey_passphrase: "{{ root_ca_key_cert_options_overide.key_pass|d(omit) }}"

    - set_fact:
        ca_key_cert_options_overide: "{{ root_ca_key_cert_options_overide }}"
    - import_tasks: ca_operation.yml