---
- name: Create intermediate CA certificate
  block:
    - set_fact:
        intermediate_ca_key_cert_options_overide: "{{ 
            intermediate_ca_key_cert_options|combine(intermediate_ca_key_options_template)|combine(
              {
                'name': intermediate_ca_key_cert_options.cert_common_name|d(intermediate_ca_key_cert_options.cert_name)|d(intermediate_ca_key_cert_options.name)
              }
            )|combine(
                { 'base_path': intermediate_ca_key_cert_options.ca_base_path|d(certificates_base_path)+'/intermediate-ca/'+intermediate_ca_key_cert_options.cert_common_name|d(intermediate_ca_key_cert_options.cert_name)|d(intermediate_ca_key_cert_options.name)}
              if not intermediate_ca_key_cert_options.base_path|d(false) else
                {}
            )
          }}" # 'key_usage': ['digitalSignature', 'keyCertSign', 'cRLSign'],

    - include_tasks: generate_key_csr.yml
      vars:
        key_cert_options_overide: "{{ intermediate_ca_key_cert_options_overide }}"

    - include_tasks: ca_sign.yml
      vars:
        cert_options_overide: "{{ intermediate_ca_key_cert_options_overide }}"

    - import_tasks: ca_operation.yml
      vars:
        ca_key_cert_options_overide: "{{ intermediate_ca_key_cert_options_overide }}"