---
# tasks file for openssl_CA

# https://superuser.com/questions/738612/openssl-ca-keyusage-extension

- when: intermediate_ca is defined
  name: Generate CAs certificate recursivly
  include_tasks: generate_root_ca.yml
  loop: "{{ root_ca }}"
  loop_control:
    loop_var: root_ca_key_cert_options

- when: intermediate_ca is defined
  import_tasks: ca_operation.yml
  vars:
    ca_key_cert_options_overide: "{{ { 'intermediate_ca': intermediate_ca } }}"

- when: self_signed is defined
  name: Generate self signed certificate
  include_tasks: generate_self_signed_certificate.yml
  loop: "{{ self_signed }}"
  loop_control:
    loop_var: self_signed_key_cert_options
